const c=document.getElementById("game"),x=c.getContext("2d"),jetI=new Image(),rockI=new Image();jetI.src="assets/space_jet.png";rockI.src="assets/space_rock.png";let W,H,dpr,jet,rocks,lasers,parts,stars,score,lives,over,last,spawn,fire;const keys={};
function size(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*dpr;c.height=H*dpr;c.style.width=W+"px";c.style.height=H+"px";x.setTransform(dpr,0,0,dpr,0,0)}
function reset(){jet={x:W/2,y:H-105,w:82,h:100,s:470};rocks=[];lasers=[];parts=[];stars=Array.from({length:220},()=>({x:Math.random()*W,y:Math.random()*H,s:.3+Math.random()*1.8,z:.3+Math.random()*.7}));score=0;lives=3;over=false;spawn=0;fire=0;last=performance.now();document.getElementById("over").classList.add("hidden");hud()}
function hud(){scoreEl.textContent=score;rocksEl.textContent=rocks.length;livesEl.textContent=lives}
const scoreEl=document.getElementById("score"),rocksEl=document.getElementById("rocks"),livesEl=document.getElementById("lives");
function rock(){let s=42+Math.random()*54;rocks.push({x:s/2+Math.random()*(W-s),y:-s,s,vy:110+Math.random()*180,r:Math.random()*6.28,vr:(Math.random()-.5)*2})}
function shoot(){lasers.push({x:jet.x-22,y:jet.y-45,vy:-900,life:1},{x:jet.x+22,y:jet.y-45,vy:-900,life:1})}
function boom(a,b){for(let i=0;i<20;i++)parts.push({x:a,y:b,vx:(Math.random()-.5)*330,vy:(Math.random()-.5)*330,l:.35+Math.random()*.5,s:2+Math.random()*4})}
function update(dt){let dir=(keys.a||keys.arrowleft?-1:0)+(keys.d||keys.arrowright?1:0);jet.x=Math.max(45,Math.min(W-45,jet.x+dir*jet.s*dt));fire-=dt;if(fire<=0){shoot();fire=.13}spawn-=dt;if(spawn<=0){rock();spawn=Math.max(.3,.78-score*.0008)}stars.forEach(s=>{s.y+=35*s.z*dt;if(s.y>H){s.y=0;s.x=Math.random()*W}});lasers.forEach(l=>{l.y+=l.vy*dt;l.life-=dt});lasers=lasers.filter(l=>l.y>-40&&l.life>0);rocks.forEach(r=>{r.y+=r.vy*dt;r.r+=r.vr*dt});
for(let i=rocks.length-1;i>=0;i--){let r=rocks[i],hit=false;for(let j=lasers.length-1;j>=0;j--){let l=lasers[j];if(Math.abs(l.x-r.x)<r.s*.48&&Math.abs(l.y-r.y)<r.s*.48){lasers.splice(j,1);hit=true;break}}if(hit){boom(r.x,r.y);rocks.splice(i,1);score+=10;continue}if(Math.abs(r.x-jet.x)<r.s*.55+28&&Math.abs(r.y-jet.y)<r.s*.55+34){boom(jet.x,jet.y);rocks.splice(i,1);lives--;if(lives<=0){over=true;document.getElementById("final").textContent=score;document.getElementById("over").classList.remove("hidden")}}}
rocks=rocks.filter(r=>r.y<H+100);parts.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=80*dt;p.l-=dt});parts=parts.filter(p=>p.l>0);hud()}
function draw(t){x.fillStyle="#02030a";x.fillRect(0,0,W,H);let g=x.createRadialGradient(W*.5,H*.45,0,W*.5,H*.45,Math.max(W,H)*.8);g.addColorStop(0,"#172b6620");g.addColorStop(.4,"#5b16800e");g.addColorStop(1,"#0000");x.fillStyle=g;x.fillRect(0,0,W,H);x.save();x.translate(W/2,H/2);x.rotate(-.22);x.globalAlpha=.22;x.filter="blur(30px)";let b=x.createLinearGradient(-W,0,W,0);b.addColorStop(0,"#0000");b.addColorStop(.3,"#167cff");b.addColorStop(.5,"#d225ff");b.addColorStop(.68,"#ff2b9a");b.addColorStop(.9,"#1de0ff");b.addColorStop(1,"#0000");x.fillStyle=b;x.fillRect(-W,-70,W*2,140);x.restore();stars.forEach(s=>{x.fillStyle=`rgba(220,240,255,${.25+s.z*.75})`;x.fillRect(s.x,s.y,s.s,s.s)});
lasers.forEach(l=>{let q=x.createLinearGradient(l.x,l.y-30,l.x,l.y+10);q.addColorStop(0,"#fff0");q.addColorStop(.4,"#8ff");q.addColorStop(1,"#08f0");x.strokeStyle=q;x.lineWidth=5;x.beginPath();x.moveTo(l.x,l.y-30);x.lineTo(l.x,l.y+10);x.stroke()});rocks.forEach(r=>{x.save();x.translate(r.x,r.y);x.rotate(r.r);x.shadowBlur=18;x.shadowColor="#9ab0d033";x.drawImage(rockI,-r.s/2,-r.s/2,r.s,r.s);x.restore()});x.save();x.shadowBlur=25;x.shadowColor="#28b4ff88";x.drawImage(jetI,jet.x-jet.w/2,jet.y-jet.h/2,jet.w,jet.h);x.restore();parts.forEach(p=>{x.globalAlpha=Math.max(0,p.l*1.5);x.fillStyle="#78dcff";x.beginPath();x.arc(p.x,p.y,p.s,0,Math.PI*2);x.fill();x.globalAlpha=1})}
function loop(n){let dt=Math.min(.033,(n-last)/1000);last=n;if(!over)update(dt);draw(n/1000);requestAnimationFrame(loop)}addEventListener("keydown",e=>{keys[e.key.toLowerCase()]=true});addEventListener("keyup",e=>{keys[e.key.toLowerCase()]=false});addEventListener("resize",()=>{size();if(jet)jet.y=H-105});document.getElementById("restart").onclick=reset;size();reset();requestAnimationFrame(loop);